name: invelop
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path_android: 'assets/images/logo_710_599.png'
  image_path_ios: 'assets/images/invelop_logo.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: 'assets/images/invelop_logo.png' # only available for Android 8.0 devices and above
  adaptive_icon_foreground: 'assets/images/logo_432.png' # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: 'assets/images/logo_432.png' # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: '#ffffff'
