// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCahYnzkZvZUGhk-jv__Sk9sgG0xzMHkXk',
    appId: '1:635095134435:web:6aca6dea4cebe9ced815d6',
    messagingSenderId: '635095134435',
    projectId: 'invelop-a3472',
    authDomain: 'invelop-a3472.firebaseapp.com',
    storageBucket: 'invelop-a3472.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKugR-t28jHANk97p-z1lxTb_OBsaD60o',
    appId: '1:635095134435:android:65a060323b9360dad815d6',
    messagingSenderId: '635095134435',
    projectId: 'invelop-a3472',
    storageBucket: 'invelop-a3472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5MVxlOxIytcJQnU_TrMdBNbc854G9M0',
    appId: '1:635095134435:ios:9c6b3c4877fb3eb7d815d6',
    messagingSenderId: '635095134435',
    projectId: 'invelop-a3472',
    storageBucket: 'invelop-a3472.appspot.com',
    iosBundleId: 'com.example.invelop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5MVxlOxIytcJQnU_TrMdBNbc854G9M0',
    appId: '1:635095134435:ios:9c6b3c4877fb3eb7d815d6',
    messagingSenderId: '635095134435',
    projectId: 'invelop-a3472',
    storageBucket: 'invelop-a3472.appspot.com',
    iosBundleId: 'com.example.invelop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCahYnzkZvZUGhk-jv__Sk9sgG0xzMHkXk',
    appId: '1:635095134435:web:8496807003981703d815d6',
    messagingSenderId: '635095134435',
    projectId: 'invelop-a3472',
    authDomain: 'invelop-a3472.firebaseapp.com',
    storageBucket: 'invelop-a3472.appspot.com',
  );

}